In [6]:
#Problem_1:

import numpy as np

# 1. Empty array 2x2
arr_empty = np.empty((2, 2))
print("Empty 2x2 array:\n", arr_empty)

# 2. All-one array 4x2
arr_ones = np.ones((4, 2))
print("\nAll ones 4x2 array:\n", arr_ones)

# 3. Array filled with a value (example: 7)
arr_full = np.full((3, 3), 7)
print("\nFull array filled with 7:\n", arr_full)

# 4. Zeros with same shape/type as another array
a = np.array([[1, 2], [3, 4]])
arr_zeros_like = np.zeros_like(a)
print("\nZeros like array a:\n", arr_zeros_like)

# 5. Ones with same shape/type as another array
arr_ones_like = np.ones_like(a)
print("\nOnes like array a:\n", arr_ones_like)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("\nArray from list:\n", arr_from_list)


Empty 2x2 array:
 [[4.37563414e-315 0.00000000e+000]
 [5.73116149e-322 1.36906038e-231]]

All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like array a:
 [[0 0]
 [0 0]]

Ones like array a:
 [[1 1]
 [1 1]]

Array from list:
 [1 2 3 4]


In [7]:
#Problem_2:

# 1. Array from 10 to 49
arr_range = np.arange(10, 50)
print("\nArray 10 to 49:\n", arr_range)

# 2. 3x3 matrix from 0 to 8
arr_matrix = np.arange(9).reshape(3, 3)
print("\n3x3 matrix 0 to 8:\n", arr_matrix)

# 3. Identity matrix 3x3
identity_matrix = np.eye(3)
print("\nIdentity matrix:\n", identity_matrix)

# 4. Random array of size 30 & mean
rand_arr = np.random.random(30)
print("\nMean of random array:", rand_arr.mean())

# 5. 10x10 random array: min & max
rand_10 = np.random.random((10, 10))
print("\nMin:", rand_10.min(), "Max:", rand_10.max())

# 6. Zero array with 5th element = 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\nZero array with 5th element 1:\n", zero_arr)

# 7. Reverse array
arr = np.array([1, 2, 0, 0, 4, 0])
rev_arr = arr[::-1]
print("\nReversed array:\n", rev_arr)

# 8. 2D array with border = 1, inside = 0
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("\n2D border matrix:\n", border_arr)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 checkerboard:\n", checkerboard)



Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of random array: 0.5079040929165206

Min: 0.006147275735376212 Max: 0.9919168662282848

Zero array with 5th element 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array:
 [0 4 0 0 2 1]

2D border matrix:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [12]:
#Problem_3:

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add arrays
print("\nAddition:\n", x + y)

# 2. Subtraction
print("\nSubtraction:\n", x - y)

# 3. Multiply with integer (example: 3)
print("\nMultiply x by 3:\n", x * 3)

# 4. Square each element
print("\nSquare of elements in x:\n", x ** 2)

# 5. Dot products
print("\nDot product v·w:", np.dot(v, w))
print("\nDot product x·v:\n", np.dot(x, v))
print("\nDot product x·y:\n", np.dot(x, y))

# 6. Concatenate x and y (row-wise)
xy_row = np.vstack((x, y))
print("\nRow-wise concat of x and y:\n", xy_row)

# Concatenate v and w (column-wise)
vw_col = np.vstack((v, w)).T
print("\nColumn-wise concat of v and w:\n", vw_col)

# 7. Concatenate x and v — WHY ERROR?
# x shape = (2,2)
# v shape = (2,)
# They cannot align along any axis → mismatch → ERROR


Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiply x by 3:
 [[ 3  6]
 [ 9 15]]

Square of elements in x:
 [[ 1  4]
 [ 9 25]]

Dot product v·w: 219

Dot product x·v:
 [29 77]

Dot product x·y:
 [[19 22]
 [50 58]]

Row-wise concat of x and y:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Column-wise concat of v and w:
 [[ 9 11]
 [10 12]]


In [13]:
#Problem_4:

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_check = A.dot(A_inv)
print("\nA * A^-1:\n", identity_check)

# 2. Prove AB ≠ BA
AB = A.dot(B)
BA = B.dot(A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)

# 3. Prove (AB)^T = B^T A^T
lhs = AB.T
rhs = B.T.dot(A.T)
print("\n(AB)^T:\n", lhs)
print("\nB^T A^T:\n", rhs)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]


In [14]:
#Write as matrices AX = B
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

#Solve using inverse method
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print("\nSolution using inverse method:\n", X)

#Solve using NumPy's direct solver
X2 = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve:\n", X2)


Solution using inverse method:
 [ 2.  1. -2.]

Solution using np.linalg.solve:
 [ 2.  1. -2.]
